
def localProps = new Properties()
def localPropsFile = rootProject.file('local.properties')
if (localPropsFile.exists()) { localPropsFile.withReader { localProps.load(it) } }

buildscript {
    repositories {
        google()
        mavenCentral()
    }
}
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

repositories {
    google()
    mavenCentral()
}

android {
    compileSdk 34
    defaultConfig {
        applicationId "com.base.launcher"
        minSdk 24
        targetSdk 34
        versionCode 1001
        versionName '1.0.0.1'
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        dataBinding {
            enabled = true
        }
        buildFeatures {
            aidl true
            buildConfig = true
        }
        namespace 'com.base.launcher'
        multiDexEnabled true

        // Default URL of the web panel (scheme + host!)
        buildConfigField("String", "BASE_URL", "\"https://mdm.thebeanfamily.org\"")
        // URL of the secondary address of your web panel, called when the primary host is not available.
        // Could be equal to the BASE_URL parameter
        buildConfigField("String", "SECONDARY_BASE_URL", "\"https://mdm.thebeanfamily.org\"")
        // Relative path of the web panel on the server. Keep it empty if installed in the root
        buildConfigField("String", "SERVER_PROJECT", "\"\"")
        // This parameter manages how the device ID should be set up at first start
        // "user" - user enters it manually
        // "suggest" - user can select among few predefined values (IMEI, serial, MAC)
        // "imei", "serial", "mac" - set the selected parameter as device ID without user interaction
        buildConfigField("String", "DEVICE_ID_CHOICE", "\"suggest\"")
        // Enables Push notifications. Setting it to false will stop automatic configuration updates after changing it on the server.
        buildConfigField("Boolean", "ENABLE_PUSH", "true")
        // MQTT port for Push notifications
        buildConfigField("String", "MQTT_DOMAIN", "\"${localProps['mqtt.domain'] ?: 'mqtt.thebase.vn'}\"")
        buildConfigField("Integer", "MQTT_PORT", "18883")
        buildConfigField("Boolean", "MQTT_TLS", "true")
        buildConfigField("Integer", "MQTT_QOS", "1")
        buildConfigField("String", "MQTT_USERNAME", "\"${localProps['mqtt.username'] ?: ''}\"")
        buildConfigField("String", "MQTT_PASSWORD", "\"${localProps['mqtt.password'] ?: ''}\"")
        // Set this parameter to true if you'll grant system privileges to Base MDM (signing it by system keys).
        buildConfigField("Boolean", "SYSTEM_PRIVILEGES", "true")
        // Set this parameter to true if you'd like to trust every certificate, for example, self-signed
        buildConfigField("Boolean", "TRUST_ANY_CERTIFICATE", "false")
        // A shared secret to sign server config requests and MQTT (Push) messages
        buildConfigField("String", "REQUEST_SIGNATURE", "\"${localProps['request.signature'] ?: ''}\"")
        // Set this parameter to true if the server signature should be checked
        buildConfigField("Boolean", "CHECK_SIGNATURE", "false")
        // ANR watchdog flag (for testing purposes only as this watchdog may drain the resources!)
        buildConfigField("Boolean", "ANR_WATCHDOG", "false")
        // If set to true, the server URL will be requested in UI in non-MDM mode even if it is hardcoded in build.gradle
        buildConfigField("Boolean", "REQUEST_SERVER_URL", "true")
        // Foreground service for MQTT: prevents OS from killing MQTT service on weak devices
        buildConfigField("Boolean", "MQTT_SERVICE_FOREGROUND", "true")
        // Set Base MDM to default launcher at early time of the first start
        buildConfigField("Boolean", "SET_DEFAULT_LAUNCHER_EARLY", "true")
        // Adjust application selection on TV boxes
        buildConfigField("Boolean", "SELECTED_ITEM_BY_CLICK", "false")
        // Adjust application selection on TV boxes
        buildConfigField("Boolean", "DISABLE_ORIENTATION_LOCK", "false")
        // API key for the authorization of privileged library requests
        buildConfigField("String", "LIBRARY_API_KEY", "\"${localProps['library.api.key'] ?: ''}\"")
        // Use accessibility services to control unwanted apps
        buildConfigField("Boolean", "USE_ACCESSIBILITY", "false")
    }

    signingConfigs {
        config {
            storeFile file(localProps['keystore.path'] ?: 'C:\\Git\\android_keystores\\base\\base.jks')
            keyAlias = localProps['keystore.alias'] ?: 'base'
            keyPassword localProps['keystore.password']
            storePassword localProps['keystore.password']
        }
        debug {
            storeFile file(localProps['keystore.path'] ?: 'C:\\Git\\android_keystores\\base\\base.jks')
            keyAlias = localProps['keystore.alias'] ?: 'base'
            keyPassword localProps['keystore.password']
            storePassword localProps['keystore.password']
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            debuggable false
            signingConfig signingConfigs.config
            buildConfigField("Boolean", "DEVICE_ADMIN_DEBUG", "false")
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
            buildConfigField("Boolean", "DEVICE_ADMIN_DEBUG", "true")
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.md'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.md'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }

    flavorDimensions "all"

    productFlavors {
        base { }
    }
}

static def releaseTime() {
    return new Date().format("ddMMyyyy", TimeZone.getTimeZone("UTC"))
}

android.applicationVariants.all {
    variant -> variant.outputs.all {
        outputFileName = "base_agent_${variant.buildType.name}_v${variant.versionName}_${releaseTime()}.apk"
    }
}


dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    testImplementation 'junit:junit:4.13.2'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'
    // Core AndroidX test libraries
    androidTestImplementation 'androidx.test:rules:1.5.0'

    // JUnit for Android instrumentation tests
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'

    // Optional (for Espresso UI tests)
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    // MQTT messaging
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'

    // Picasso
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.1.0'

    // Retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.squareup.retrofit2:converter-jackson:2.11.0'

    // Jackson
    implementation 'com.fasterxml.jackson.core:jackson-core:2.18.3'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.18.3'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.3'
    implementation 'com.fasterxml.jackson.module:jackson-module-kotlin:2.18.3'

    // Worker
    implementation 'androidx.work:work-runtime:2.9.1'

    implementation('com.journeyapps:zxing-android-embedded:4.1.0') { transitive = false }
    implementation 'com.google.zxing:core:3.3.0'
    implementation group: 'commons-io', name: 'commons-io', version: '2.17.0'

    // JAX-B dependencies for JDK 9+
    implementation "jakarta.xml.bind:jakarta.xml.bind-api:2.3.2"
    implementation "org.glassfish.jaxb:jaxb-runtime:2.3.2"

    // Kotlin
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:2.0.21'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0'

    implementation(files("libs/ComponentLib_1.2.5_release.aar"))
    implementation(files("libs/TerminalManagerLib_1.1.0_release.aar"))

}
